CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  fullname VARCHAR(100) NOT NULL,
  role VARCHAR(50) DEFAULT 'AdminGudang',
  status VARCHAR(20) DEFAULT 'Inactive',
  activation_token VARCHAR(128),
  reset_token VARCHAR(128),
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
